name: annotation
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - biopython==1.78
  - prokka==1.14.6
  - eggnog-mapper==2.1.3
  - run-dbcan==2.0.11
  - networkx==2.6.3
  - ncbi-amrfinderplus==3.10.18
