name: gutsmash
channels:
 - conda-forge
 - bioconda
 - defaults
dependencies:
 - hmmer2=2.3.2
 - hmmer=3.3.2
 - diamond=0.9.19
 - fasttree=2.1.11
 - prodigal=2.6.3
 - blast=2.13.0
 - muscle=3.8.1551
 - glimmerhmm=3.0.4
 - biopython=1.76
 - helperlibs=0.1.9
 - bcbio-gff=0.6.6
 - pysvg-py3=0.2.2.post3
 - scikit-learn=0.22.1
 - matplotlib=3.2.1
 - pyscss=1.3.7
 - jinja2=2.11.1
 - pandas=1.5.3
 - tqdm=4.65.0
