# Input list of genome files

input_file: "/rds/user/aa2369/hpc-work/scripts/snakemake/genofan/test/input_files.txt"

# Directory containing necessary DBs

db_dir: "/rfs/project/rfs-42V0sRc5Rk8/databases"
gutsmash_dir: "/rds/project/rds-aFEMMKDjWlo/software/gutsmash"

# Number of cores

ncores: 4
