# Input list of genome files

input_file: "/rds/project/rds-aFEMMKDjWlo/aalmeida/antipath/strains/phylo/GUT_GENOME096063/GUT_GENOME096063_paths.txt"

# Directory containing necessary DBs

db_dir: "/rds/project/rds-aFEMMKDjWlo/rfs_data/databases"
gutsmash_dir: "/rds/project/rds-aFEMMKDjWlo/software/gutsmash"

# Number of cores

ncores: 4
