# Input list of genome files

input_file: "/rds/project/rds-aFEMMKDjWlo/aalmeida/test/input.txt"

# Directory containing necessary DBs

db_dir: "/rfs/project/rfs-42V0sRc5Rk8/databases"

# Number of cores

ncores: 4
